name: build-sinan-chrome-extension

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Verify dist directory
        run: |
          echo "Checking dist directory..."
          ls -la dist/
          if [ -d "dist" ]; then
            echo "✅ Dist directory created successfully"
            echo "📦 Dist directory size: $(du -sh dist/ | cut -f1)"
          else
            echo "❌ Dist directory not found!"
            exit 1
          fi

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
